GET http://localhost:8001/

### 
GET http://localhost:8001/about

###

GET http://localhost:8001/tickets

###

GET http://localhost:8001/animals/44



###

POST http://localhost:8001/animals
Content-Type: application/json

{
  "name": "Lion",
  "count" : 94
}


###

DELETE http://localhost:8001/animals/2



