GET http://localhost:8001/

### 
GET http://localhost:8001/about

###

GET http://localhost:8001/tickets

###

GET http://localhost:8001/animals/44



###

POST http://localhost:8001/animals
Content-Type: application/json

{
  "name": "Lion",
  "count" : 94
}


###

DELETE http://localhost:8001/animals/5

###

PATCH http://localhost:8001/animals/4
Content-Type: application/json

{
  "name": "Giraffe",
  "count" : 10
}

###

POST http://localhost:8001/seacritters
Content-Type: application/json

{
  "name": "Spider Crab",
  "count" : 4
}


###
DELETE http://localhost:8001/seacritters/5


###

PATCH http://localhost:8001/seacritters/1
Content-Type: application/json

{
  "count" : 5
}

